server:
  port: 8050
  servlet:
    context-path: /api

spring:
  application:
    name: mall-backend
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #url: jdbc:mysql://sh-cynosdbmysql-grp-ht2vy34k.sql.tencentcdb.com:25851/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    #password: litheme2024!!!
    password: 123456
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:/mapper/*.xml

jwt:
  secret: mall-secret-key-2024-very-long-and-secure-jwt-signing-key-for-hmac-sha256-algorithm-minimum-256-bits-required
  expiration: 604800 # 7天，单位：秒

logging:
  level:
    com.mall: debug
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

file:
  upload:
    path: /uploads/
    base-url: http://localhost:8050/api/uploads/